### ISSUE TITLE
Exception: Full Account Request failed with status code 503: {"message":"Service Unavailable"}

### ISSUE THREAD

**Issue by Cfomodz** [NelsonDane/fennel-invest-api#13]
It seems as though when there is an existing pkl that shouldn't be expired is loaded (this can occur from logging into the account from mobile and getting a new email code) then it moves forward without checking authentication somehow. I have not debugged this, and it could be a local modification I have made that is leading to this, so sorry for the poor issue, I just wanted to bring it up in case it's something others have noticed and fixed or noticed and worked around thinking it was just happening to them.

Fix: By deleting the .pkl file it prompts for a new 2FA and everything is normal.

Suggestion: If a 503 [or 401, 403] is received, start auth over - this could obviously be handled on the implementation side, and if it were implemented at the wrapper level, then the auth would need to timestamp the previous attempt or in some other way handle an inf loop of 503s due to actual unavailability.

**Comment by NelsonDane** [comment]
Someone else also reached out with this issue today, and I'm very curious why it is occurring. Perhaps you could share a whole trace so I can see exactly what line is throwing the error? The other person's error occurred after login when trying to run `get_full_accounts()`, which suggests that login occurred normally, then the error occurred, which is very weird.

The way login works currently is that it loads the pkl file, then checks it using `_verify_login()`. This function hits a protected endpoint (`account_ids`) to see if the cookies are valid. If not, it tries to refresh them and then tries again. Finally, if the refresh fails or an Exception occurs, it clears the cookies and continues logging in as normal (at least it's supposed to). Perhaps there's an edge case that is sneaking through :(

**Comment by NelsonDane** [comment]
I believe this is fixed in newer/current versions. If not please reopen this issue

**Comment by Cfomodz** [comment]
> Hey [@cortozld](https://github.com/cortozld) , I'm in the process of rewriting the API now that an official version has dropped. Hopefully this should be finished soon

Are you going to release it as this repo? Let me know if you want me to do any of it since I've unsurprisingly implemented full Fennel automation again in the last 72 hours ;)
