### ISSUE TITLE
Trading Suspended

### ISSUE THREAD

**Issue by Cfomodz** [NelsonDane/fennel-invest-api#14]
I received an image from someone using the repo

![image](https://github.com/NelsonDane/fennel-invest-api/assets/31261577/2704ec2c-700f-40c1-9216-14e565de74c6)

I would stop using the repo for the time being. I have reached out to see if we could establish a working relationship to implement an authorized connection.

**Comment by NelsonDane** [comment]
Thanks for reaching out. People have been in contact with me the past few days, and the discrepancy issue they're referring to has been resolved with the `1.0.9` update I pushed earlier this week. Unfortunately, I can't do anything on my side to force upgrades, but I urged everyone I knew to upgrade to that version and I'll put a note in the README. Although I was able to fix the issue as soon as I was able, it's one of the risks of using an unofficial API like this tool.
