### ISSUE TITLE
Multiple Accounts?

### ISSUE THREAD

**Issue by yoberner** [NelsonDane/fennel-invest-api#15]
Hi @NelsonDane ,
Can this be used to trade with all my Fennel brokerage accounts at once? Buy the same stock across all of them? I have multiple accounts under my email. 
What about if I am using the [auto-rsa](https://github.com/NelsonDane/auto-rsa) repo?
Thanks.

**Comment by NelsonDane** [comment]
Yes.

**Comment by yoberner** [comment]
How is this done? Should all the accounts be entered or does it automatically trade on all fennel accounts?

**Comment by NelsonDane** [comment]
This is an API, so what it does depends on what code you write. If you want it to only act on one account it can do that, or if you want it to run on all accounts using a loop it can do that too. Please see the examples in the README
