### ISSUE TITLE
Unidentified keyword argument

### ISSUE THREAD

**Issue by alessiobra** [NelsonDane/fennel-invest-api#17]
![image](https://github.com/user-attachments/assets/703cb08f-05e4-4a48-a989-cd2e514944b5)

**Comment by alessiobra** [comment]
This is when trying to place an order

**Comment by NelsonDane** [comment]
Sorry, I had the wrong word in the README. This should be fixed as of e74e2f6fe0ad3c6ad53657af1e6008b11397e772
