### ISSUE TITLE
issue ordering

### ISSUE THREAD

**Issue by majestic1222** [NelsonDane/fennel-invest-api#20]
when i submit an order it goes to pending in my account but then errors shortly after. any fix for this?

**Comment by FlintSH** [comment]
What stock? Any other info you can provide?

**Comment by NelsonDane** [comment]
Can you provide more info @majestic1222 ?

Otherwise I'm closing

**Comment by NelsonDane** [comment]
This is normal behavior for Fennel, they don't execute orders right away so they pend for a (potentially long) time.
