### ISSUE TITLE
Short Tickers Ordering

### ISSUE THREAD

**Issue by TravisLedo** [NelsonDane/fennel-invest-api#21]
Just noticed this happened twice with 2 tickers that were only 2 letters long. When placing a buy order, it cannot find the ISIN for the stock. But you can buy manually from the app if you search for the company name. Searching on the app by ticker also fails. Not sure if there's a way to buy by company name insead?

**Comment by NelsonDane** [comment]
Unfortunately, Fennel doesn't provide an easy way to retrieve a stock's `ISIN` (at least that I'm aware of). The only way to get that is by Searching (equivalent to typing in the Search bar in the app), but for short tickers, they don't come up in the first give results. In this API, I can control how many results are sent back, so I've increased that. I noticed that this seemed to get the short tickers to come up. So hopefully this fixes it for now.

**Comment by andresh3** [comment]
Hey,

I implemented what I can only call a "grotesque fix" for this problem; all I did was add the ISIN number as an optional parameter in the `Fennel.place_order(...)` method. If you want to sell existing holdings you would look at your existing holdings and access the ISIN by `fennel.get_stock_holdings(account_number)[*index*]['isin']` and then manually specify that ISIN somehow in your script, i.e.

```py
isin=False
if isin_provided is True:
    isin=provided_isin
fennel.place_order(account_number, 'TICKER', 999, 'sell', isin=isin)
```

To purchase, my best offer is to manually purchase a share on the app somehow, and then look at the ISIN from there.

https://github.com/andresh3/fennel-invest-api

**Comment by NelsonDane** [comment]
💀

**Comment by NelsonDane** [comment]
While that is a solution @andresh3, it opens the door for people to pass the wrong `isin` to the order, which has happened on accident before and caused Fennel to lock/ban accounts because it was filling their orders with mismatched `isin`s and tickers.
