### ISSUE TITLE
No Way to Sign out via API

### ISSUE THREAD

**Issue by yuvansundrani** [NelsonDane/fennel-invest-api#22]
Hi! 

I am trying to sign out via the API, in order to sign in to a diff account with a different email, but I am unable to. 

Order of operation to replicate this:
- Sign in with an account x
- Saw that I have 0 account ID's in this account
- Wanted to sign in with account y (has 3 account ID's), but due to these lines in 'login', the bearer token of account x wasn't letting me sign in with a different account 
```
def login(self, email, wait_for_code=True, code=None):
        # If creds exist, check if they are valid/try to refresh
        if self.Bearer is not None and self._verify_login():     # this line is returning true due to account x being logged in previously
            return True

```
- I commented out occuring lines above ^ and was able to get the 2FA prompt for account y, got the email, entered it, said i was signed in, but said i have 0 account ID's -- So im wondering if it's using the information from account x
- I'm thinking & hoping a signOut() function would clear the tokens/cache/attributes for a fresh login :) 

Thank you!

**Comment by yuvansundrani** [comment]
I just tried to implement a kinda custom sign out like so:
```
def sign_out():
    sign_out = fennel._clear_credentials()

    if fennel.Bearer == None and fennel.Refresh == None and fennel.ID_Token == None:
        print("credentials cleaned, sign out successful")
        return True
    else:
        print("error signing out, still signed in")
        return False
 
```

After signing into account x, i "sign out" via this method, and login with account y (which has 3 accounts), it asks me 2FA (yay!) and signs me in, but when i try to get my account ID's its still `[]`

**Comment by NelsonDane** [comment]
You're right, there's currently no way to sign out of a session.

However, when you initialize a `Fennel()` object you can pass in a location to store the cookies. So you could just make 2 different `Fennel()` objects and give them different pkl file names. That would make sure they use the correct credentials for transactions.

**Comment by ImRafat** [comment]
Hello,

I am also having a tough time with this. Anyway you can provide a code example of a potential workaround. Trying to trigger trades for 5 people but unable to do so because of this. I am stuck with the session of the first person I authenticated. Where is this session info saved? Anyway I can force to reset the session?

**Comment by robschwartz** [comment]
@yuvansundrani have you figured this out? Running into the same issue.

**Comment by yuvansundrani** [comment]
U gotta delete the fennel_credentials.pkl file to kinda "reset" or "sign out"
