### ISSUE TITLE
Error Selling: Failed to find ISIN for stock with ticker...

### ISSUE THREAD

**Issue by yuvansundrani** [NelsonDane/fennel-invest-api#23]
Hi, i've been using this module for quite a while and never had trouble any of the functions, but this morning I was selling a stock and I got this error:

![Screenshot_2024-11-05_at_9 34 21_AM](https://github.com/user-attachments/assets/7bd117bb-de5d-4b19-a9e5-c74e48840a21)

I tried selling it like how I usually do and all the fields were valid. This while market was open. I thought maybe fennel wasn't able to execute orders right now, but it let me sell my position manually on the app? 

I see that it checks that case in the source code when trying to trade:
`
        isin = self.get_stock_isin(ticker)
        if isin is None:
            raise Exception(f"Failed to find ISIN for stock with ticker {ticker}")

`

However, im just wondering in **what cases is the isin unable to be found**? Is it the source code, fennel services, something external? 

Please let me know if you have experienced anything of the sort or any idea what could have gone wrong here?

**Comment by NelsonDane** [comment]
This has to do with a certain 2 letter ticker. To sell a stock, Fennel requires that we provide the `isin`, which is a special code for the stock. However, as I explained [here](https://github.com/NelsonDane/fennel-invest-api/issues/21#issuecomment-2397568601), Fennel doesn't provide a simple way to "lookup" a stock's `isin`. The only way is through the app's search bar. However, the Fennel's search bar is very bad, so searching for short tickers usually doesn't yield any results. You can try this by searching for the ticker in the Fennel app.  That's what causes the exception.

**Comment by NelsonDane** [comment]
This is fixed now. If selling and the `isin` isn't found through searching, it pulls it from the user's holdings.

**Comment by yuvansundrani** [comment]
Awesome thanks! It was working shortly after and I didnt change any code, probably just from fennel mishap
