### ISSUE TITLE
_verify_filepath will fail if the credentials file doesn't exist but the folder does.

### ISSUE THREAD

**Issue by terose73** [NelsonDane/fennel-invest-api#3]
`_verify_credentials` will trigger an exception if the credentials file doesn't exist yet (i.e.`_save_credentials` has never completed), but the folder already does exist.

I think this line can be changed to `if not os.path.exists(self.path):`.

https://github.com/NelsonDane/fennel-invest-api/blob/014b1f6341cf1612a992e75091f1072a8472dc60/fennel_invest_api/fennel.py#L39

**Comment by NelsonDane** [comment]
Thanks, good catch! Fixed in 11360a889ed3bc326c70e116ebfc03753821d0ef
