### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by gbbmiler** [NelsonDane/fennel-invest-api#6]
Reading between the lines of the readme it seems that this is licensed for other people to use, but there is no license file to make that explicit or to explain under what terms it is licensed. Any chance you could add a LICENSE file? I’d suggest a permissive open source license like the Apache or MIT licenses if your goal is to make it as easy as possible to use, which sounds like it was your goal.

**Comment by NelsonDane** [comment]
Thanks for the comment, this was something that slipped my mind haha.

I've added the MIT license in 89f72e8dc13a90aecc075fdafb61202a6606c368 to follow similar projects, such as the [schwab-api](https://github.com/itsjafer/schwab-api), [robin_stocks](https://github.com/jmfernandes/robin_stocks), and [webull](https://github.com/tedchou12/webull) repositories.

Thanks for bringing this to my attention!
